### ISSUE TITLE
custom drop message doesn't work

### ISSUE THREAD

**Issue by Sylensky** [LMBishop/CommandToItem#5]
Hi,
on the latest version of CommandToItem the custom drop message if the players inventory is full doesn't work as it is always displaying the default message.
My config looks like this:
```
  CustomItem:
    options:
      permission-required: false
      drop-if-full-inventory: true
    messages:
      receive-item-inventory-full: "&2Your inventory is full and your &a%item%&2 was dropped at your feet."
```
It displays always the default message which is
`"&6You have been given %item%&6, but it was dropped at your feet because your inventory is full."`
